### ISSUE TITLE
proxy / vps list tor usage for c2 servers

### ISSUE THREAD

**Issue by s-b-repo** [polymaster3313/terylene#17]
is it possible to use proxys or vps  from lists or use tor for c2 communication to bots

**Comment by tcpfin-dev** [comment]
It is possible to use proxies for the C2 , but its gonna be hard , as the whole terylene infrastructure relies on zeromq communication. Its not really easy to just forward zmq packets using normal TCP proxies, since zeromq sockets are heavily optimized version of TCP and tricky to work with (https://rfc.zeromq.org/spec/23/). I would hopefully add a zmq proxy in the future , to protect the C2 ip. However, this whole infrastructure is decentralized, so i wont see the big use of that.

**Comment by tcpfin-dev** [comment]
No response, closing the issue
